syntax = "proto3";
package FP.Hunt;

import "MetaCommon.proto";
import "MetaBloodLine.proto";
import "MetaMissionBag.proto";
import "MetaTelemetry.proto";

enum MetaReqType {
  option allow_alias = true;
  Start_Client = 0;
  NoReq = 0;
  Req_BuyItem = 1;
  Req_CharSellItem = 2;
  Req_CharRemoveItem = 3;
  Req_IncPrestige = 4;
  Req_CharAddTrait = 5;
  Req_CharRemoveTrait = 6;
  Req_CharAddHealthChunk = 7;
  Req_CharPutItemInSlot = 8;
  Req_CharDecAmountItemInSlot = 9;
  Req_SetCurrChar = 10;
  Req_DeleteActiveChar = 11;
  Req_DeleteInactiveChar = 12;
  Req_SetBloodLineName = 13;
  Req_AddCharFromRecruits = 14;
  Req_ClearMissionBag = 15;
  Req_CharRetire = 16;
  Req_GenerateRecruits = 17;
  Req_CheckForAutomaticRecruits = 18;
  Req_DoCraft = 20;
  Req_OpenLootBox = 21;
  Req_BuyBlueprint = 22;
  Req_SetQuickPlayClass = 23;
  Req_SetQuickPlayModel = 24;
  Req_ClaimGoalReward = 25;
  Req_AddCharFromRecruitsQuickPlay = 26;
  Req_ResetBloodLinePrePermaDeath = 27;
  Req_SellItemFromArsenal = 28;
  Req_RemoveItemFromArsenal = 29;
  Req_RefreshTimedGoals = 30;
  Req_CharRemoveAllTraits = 31;
  Req_BuyExtraHunterSlot = 32;
  Req_CharRemoveLastHealthChunk = 33;
  Req_UnlockLegendaryItem = 34;
  Req_UnlockLegendaryChar = 35;
  Req_AddCharFromLegendary = 36;
  Req_PutItemInLoadoutSlot = 37;
  Req_CharCleanItemInstanceMud = 38;
  Req_ArsenalCleanItemInstanceMud = 39;
  Req_ClearLoadout = 40;
  Req_GenerateQuickPlayModels = 41;
  Req_NotifyDlcRevoked = 42;
  Req_GoalsResetCompletion = 43;
  Req_BuyItemAndEquip = 44;
  Req_UpdateTwitchRewards = 45;
  Req_ClaimRewardTrackCheckpoints = 46;
  Req_CharRemoveAllItemsFromGroupSlot = 47;
  Req_ClaimRewardTrackSpecificCheckpoint = 48;
  Req_Ping = 49;
  Req_LiveEventSetUiGlobalFlag = 50;
  Req_LiveEventSetUiMetaStageFlag = 51;
  Req_ClearLatestOfflineRewards = 52;
  Req_BuyLiveEventBundle = 53;
  Req_LiveEventSetFirstMetaStage = 54;
  Req_BuyExtraLoadoutSlot = 55;
  Req_SaveCurrentHunterIntoLoadoutSlot = 56;
  Req_LoadCurrentHunterFromLoadoutSlot = 57;
  Req_SetLoadoutName = 58;
  Req_ActivateLiveEventBoost = 59;
  Req_DoDiceRoll = 60;
  Req_BuyDiceRoll = 61;
  Req_BuyDiscountedBundle = 62;
  Req_BuyLiveEventPointsPack = 63;
  Req_UnlockMetaObject = 64;
  Req_RefreshTimedQuests = 65;
  Req_ClaimMultipleGoalRewards = 66;
  Req_SequentialPackBuyNextElem = 67;
  Req_SequentialPackReshuffle = 68;
  Req_RedeemCode = 69;
  Req_AttachCharmToItem = 70;
  Req_StartQuestLinesGoal = 71;
  Req_CancelQuestLinesGoal = 72;
  Req_RefreshQuestLines = 73;
  Req_CharSetSlotSkin = 74;
  Req_CharRearrangeTools = 75;
  Req_SetUiGlobalFlag = 76;
  Req_SellItemFromArsenalAllInstances = 77;
  Req_BuyLiveEventPoints = 78;
  Req_CharSetHealthChunks = 79;
  Req_SetProfileCustomizationSlot = 80;
  Req_EnableMetaObject = 81;
  Req_CharSetDefaultHealthChunks = 82;
  Req_StoryChallengeUnlock = 83;
  Req_StoryChallengeChapterRewardClaim = 84;
  Req_StoryChallengeSetToTrack = 85;
  Req_LegacyPassAcquireChapterReward = 86;
  Req_RearrangeToolsLoadoutSlot = 87;
  ReqUsableInMission = 100;
  Req_TutorialEnable = 101;
  Req_TutorialSetStepDone = 102;
  Req_TutorialDone = 103;
  Req_NotifyDlcOwned = 104;
  Req_NotifyBoosterPackAcquired = 105;
  Req_NotifyBoosterPackPlatformError = 106;
  Req_AimModeSelectionDone = 107;
  Req_ClearExpiredGemsList = 108;
  Req_UserReport = 109;
  Req_SetOptOutPublicStats = 110;
  Req_GetFullBloodLine = 111;
  Req_DumpUnfinishedMissionBag = 112;
  Req_OnClientLoggedIn = 113;
  Start_Cheats = 150;
  Cheat_RewardLootPool = 151;
  Cheat_ReloadDataBaseRecruitFiles = 152;
  Cheat_UnlockAllLegendaryHunters = 153;
  Cheat_UnlockAllDlcs = 154;
  Cheat_StoryChallengeUnlock = 155;
  Cheat_StoreChallengeFinishChapter = 156;
  Cheat_StoryChallengeReset = 157;
  Cheat_StoryChallengesForceFullCheck = 158;
  Test_SetStoryChallengeTimes = 159;
  Cheat_SetSigilAmount = 160;
  Cheat_SetGold = 201;
  Cheat_SetExp = 202;
  Cheat_SetRank = 203;
  Cheat_SetPrestige = 204;
  Cheat_AddItem = 205;
  Cheat_ResetBloodLine = 206;
  Cheat_CharKill = 207;
  Cheat_CharReactivate = 208;
  Cheat_CharSetExp = 209;
  Cheat_CharSetLevel = 210;
  Cheat_CharLevelUp = 211;
  Cheat_CharSetHunterPoints = 212;
  Cheat_CharRemoveAllHealthChunks = 213;
  Cheat_CharSetName = 214;
  Cheat_CharSetModel = 215;
  Cheat_CharSetGender = 216;
  Cheat_AddCharFromPredefinedDemo = 217;
  Cheat_UnlockAndAddAllItems = 218;
  Cheat_DoRewardRedeemRewardPack = 219;
  Cheat_ClearMissionBag = 220;
  Cheat_GenerateRecruits = 221;
  Cheat_SetStats = 222;
  Cheat_CharSetStats = 223;
  Cheat_SetReleasePack = 224;
  Cheat_LockUnlockBlueprint = 225;
  Cheat_ActivateDeactivateGoal = 226;
  Cheat_SetGems = 227;
  Cheat_CompleteGoal = 228;
  Cheat_SetPvpRating = 229;
  Cheat_ForceTimedGoalSlotRegen = 230;
  Cheat_ClearArsenal = 231;
  Cheat_CharRemoveTrait = 232;
  Cheat_LockUnlockItem = 233;
  Cheat_UncompleteGoal = 234;
  Cheat_LockUnlockLegendaryChar = 235;
  Cheat_AddCharFromLegendary = 236;
  Cheat_ArsenalSetItemInstanceMud = 237;
  Cheat_CharSetItemInstanceMud = 238;
  Cheat_CharAddTrait = 239;
  Cheat_SetUnsetDLCAsOwned = 240;
  Cheat_BuyBoosterPack = 241;
  Cheat_SetGoalToNearCompletion = 242;
  Cheat_SetBloodLineToPreReleaseVersion = 243;
  Cheat_SetQuickPlayModel = 244;
  Cheat_AddToQuickPlayRecruits = 245;
  Cheat_SetHunterSlots = 246;
  Cheat_SetCurrDateForGemsExpirationProcess = 247;
  Cheat_TutorialSetStepUndone = 248;
  Cheat_SuspendResumeGoal = 249;
  Cheat_RemoveLiveEventBoost = 250;
  Cheat_AddProgressToRewardTrack = 251;
  Cheat_SetLiveEventBoost = 252;
  Cheat_StartLiveEvent = 253;
  Cheat_EndLiveEvent = 254;
  Cheat_SetLiveEventPoints = 255;
  Cheat_SetGoalProgress = 256;
  Cheat_SetTimedGoalExpirationToNow = 257;
  Cheat_BuyLiveEventBundle = 258;
  Cheat_LockUnlockTrait = 259;
  Cheat_CharIncAmountItemInSlot = 260;
  Cheat_UnhideAllTraitsAndItems = 261;
  Cheat_SetBloodLineFullData = 262;
  Cheat_SetFbeTimesStacked = 264;
  Cheat_CharSetFbeTime = 265;
  Cheat_SetFbeStackTime = 266;
  Cheat_SetDiceRollProgress = 267;
  Cheat_SetDiceRollAvailableRolls = 268;
  Cheat_SetDiceRollResetTime = 269;
  Cheat_DoDiceRoll = 270;
  Cheat_ResetLiveEventLoyaltyBonus = 271;
  Cheat_BuyLiveEventPointsPack = 272;
  Cheat_ResetLiveEventBundlesAndPointPacks = 273;
  Cheat_ResetTimedQuests = 274;
  Cheat_LockUnlockMetaObject = 275;
  Cheat_SequentialPackReset = 276;
  Cheat_EnableLiveEventPremium = 277;
  Cheat_SetEvolvingHunterUnlockedStages = 278;
  Cheat_CharSetStage = 279;
  Cheat_CheckSteamAppOwnership = 280;
  Cheat_CheckAndSetSteamOwnershipOfAllDlc = 281;
  Cheat_ClearRedeemCodesHistory = 282;
  Cheat_DecreaseLiveEventBoostDuration = 283;
  Cheat_ResetServersDowntimeLastCheck = 284;
  Cheat_ActivateQuestLine = 285;
  Cheat_DeactivateQuestLine = 286;
  Cheat_ResetQuestLine = 287;
  Cheat_OnlineTimeStatsReset = 288;
  Cheat_OnlineTimeHistoryEdit = 289;
  Cheat_OnlineTimeSetTotal = 290;
  Cheat_AddCharFromPredefinedGeneric = 291;
  Cheat_UnlockActsFromQuestLine = 292;
  Cheat_CharSetCustomAttribute = 293;
  Cheat_CharSetSlotSkin = 296;
  Cheat_SetSequentialPacksNextReshuffleResetTime = 297;
  End_Cheats = 298;
  End_Client = 299;
  Start_GM_Cmds = 300;
  GM_AddItem = 301;
  GM_RemoveItemFromArsenal = 302;
  GM_IncPrestige = 303;
  GM_SetPrestige = 304;
  GM_SetGold = 305;
  GM_SetExp = 306;
  GM_SetRank = 307;
  GM_GenerateRecruits = 308;
  GM_ResetBloodLine = 309;
  GM_SetBloodLineData = 310;
  GM_ClearMissionBag = 311;
  GM_SetStats = 312;
  GM_LockUnlockBlueprint = 313;
  GM_SetGems = 314;
  GM_ActivateDeactivateGoal = 315;
  GM_CompleteGoal = 316;
  GM_SuspendResumeGoal = 365;
  GM_SetPvPRating = 317;
  GM_ClearArsenal = 318;
  GM_LockUnlockItem = 319;
  GM_ArsenalSetItemInstanceMud = 400;
  GM_SetUnsetDLCAsOwned = 401;
  GM_SetHunterSlots = 402;
  GM_SetLiveEventBoost = 403;
  GM_SetLiveEventPoints = 404;
  GM_AddLiveEventBundle = 405;
  GM_LockUnlockTrait = 406;
  GM_ModifyLiveEventPoints = 407;
  GM_ModifyGold = 408;
  GM_ModifyExp = 409;
  GM_ModifyRank = 410;
  GM_ModifyGems = 411;
  GM_ModifyPrestige = 412;
  GM_ModifyHunterSlots = 413;
  GM_EnableLiveEventPremium = 414;
  GM_RemoveLiveEventBoost = 415;
  GM_SetEvolvingHunterUnlockedStages = 416;
  GM_CheckSteamAppOwnership = 417;
  GM_CheckAndSetSteamOwnershipOfAllDlc = 418;
  GM_LockUnlockMetaObject = 419;
  GM_StoryChallengeUnlock = 420;
  GM_StoryChallengeReset = 421;
  GM_StoryChallengeChapterFinish = 422;
  GM_LegacyPassAcquireChapterReward = 423;
  GM_LegacyPassSetSigilsAmount = 424;
  GM_LegacyPassSetSigilsSpentAmount = 425;
  GM_SetCurrChar = 320;
  GM_CharKill = 321;
  GM_CharReactivate = 323;
  GM_CharRetire = 324;
  GM_AsGame_CharRetire = 325;
  GM_DeleteActiveChar = 326;
  GM_DeleteInactiveChar = 327;
  GM_AddCharFromRecruits = 328;
  GM_AddCharFromPredefined = 329;
  GM_LockUnlockLegendaryChar = 330;
  GM_AddCharFromLegendary = 331;
  GM_CharSetExp = 350;
  GM_CharSetLevel = 351;
  GM_CharLevelUp = 352;
  GM_CharSetHunterPoints = 353;
  GM_CharRemoveAllHealthChunks = 354;
  GM_CharSetName = 355;
  GM_CharSetModel = 356;
  GM_CharSetGender = 357;
  GM_CharAddTrait = 358;
  GM_CharRemoveTrait = 359;
  GM_CharAddHealthChunk = 360;
  GM_CharPutItemInSlot = 361;
  GM_CharDecAmountItemInSlot = 362;
  GM_CharSetStats = 363;
  GM_CharRemoveLastHealthChunk = 364;
  GM_UnlockAllItemsAtOnce = 380;
  End_GM_Cmds = 499;
  Start_GFace = 500;
  GFace_AddGold = 501;
  End_GFace = 599;
}
message MetaRequest {
  FP.Hunt.MetaReqType type = 1;
  repeated int32 params = 2;
  int32 char_index = 3;
  string str_param = 4;
  FP.Hunt.MetaSerBloodLineFull blood_line_data = 5;
  int64 time_stamp = 6;
  FP.Hunt.MetaItemInstanceId item_instance_id = 7;
  string gm_id = 8;
  int64 param_int64 = 9;
  bool gmtool_ignore_time_stamp = 10;
  bool request_full_blood_line = 11;
  int32 discounts_update_counter = 12;
  int32 release_manager_update_counter = 13;
}
message MetaReqRsp {
  enum Code {
    Ok = 0;
    LesserRecruitsGenerated = 1;
    BankruptcyRecruitsGeneratedAutomatically = 2;
    ErrorsStartEnum = 10;
    Error = 11;
    NotSupportedOffline = 12;
    NotEnoughGold = 13;
    NotEnoughRank = 14;
    NotEnoughHunterPoints = 15;
    TooMuchHealth = 16;
    InvalidDualWeaponCombo = 17;
    Duplicated = 18;
    NotEnoughGoldForGenerationButCanSell = 19;
    TimeStampMistmatch = 20;
    NotEnoughGems = 21;
    GoalNotClaimable = 22;
    NonMetaError = 23;
    CouldNotEquip = 24;
    RewardTrackNotClaimable = 25;
    LiveEventNotRunning = 26;
    InvalidParameter = 27;
    ItemNull = 28;
    WrongItemType = 29;
    NotAvailableOnStore = 30;
    AlreadyOwnTooMany = 31;
    NotUnlocked = 32;
    BaseNotUnlocked = 33;
    OnlyAvailableInLiveEvent = 34;
    AlreadyDone = 35;
    NotAllowedInGameSession = 36;
    MissionBagUnfinished = 37;
    ClientDevCheat = 38;
    TooLowLevel = 39;
    CharNull = 40;
    NotAllowed = 41;
    IsTier0 = 42;
    IsNotLegendary = 43;
    NotUnlockableOnStore = 44;
    AlreadyUnlocked = 45;
    OnlyCanDoInLiveEvent = 46;
    NoItems = 47;
    NoItemInstance = 48;
    TraitNull = 49;
    AlreadyCleaned = 50;
    AlreadyCompleted = 51;
    IsDualWieldProxy = 52;
    IsDualWieldIntegral = 53;
    OnlyOneLeft = 54;
    NoChunksLeft = 55;
    UnknownChunkType = 56;
    ModelNull = 57;
    IsNotQuickPlayModel = 58;
    NotEnoughSlots = 59;
    DlcNull = 60;
    BoosterPackNull = 61;
    CantBuyMoreTimes = 62;
    NoRecruitsGenerationsLeft = 63;
    NotAllowedAnymore = 64;
    MetaStageNotFound = 65;
    DiscountsOutOfSynq = 66;
    CouldNotUpdateDiscounts = 67;
    IsHidden = 68;
    AlreadyHaveIt = 69;
    TooManyTraits = 70;
    InvalidGridPlace = 71;
    CantBuyMoreSlots = 72;
    ItemNeedsGemsForPurchase = 73;
    TwoBigWeapons = 74;
    NoAvailableDiceRolls = 75;
    CantBuy = 76;
    DiscountNotFound = 77;
    IsNotABundle = 78;
    AllAlreadyUnlocked = 79;
    NotActive = 80;
    InvalidPrice = 81;
    TooManyItemsWithFlag = 82;
    PackNull = 83;
    PackAlreadyCompleted = 84;
    NoReshufflesLeft = 85;
    ParameterOutOfRange = 86;
    IsNotEvolvingHunter = 87;
    StageNotUnlocked = 88;
    EvolvingHunterCantHaveStage0 = 89;
    DlcNotOwnedOnPlatform = 90;
    RedeemCodeInvalid = 91;
    RedeemCodeExpired = 92;
    RedeemCodeOutOfActivationLimits = 93;
    RedeemCodeAlreadyUsed = 94;
    RedeemCodeNotApplicable = 95;
    RedeemCodeRewardAlreadyClaimed = 96;
    RedeemCodeUnableToFetchReward = 97;
    IsCharm = 98;
    CharmNull = 99;
    IsNotWeapon = 100;
    QuestLinesGoalAlreadyActive = 101;
    QuestLinesGoalNotActive = 102;
    QuestLinesNoFreeSlot = 103;
    QuestLinesGoalAlreadyFinished = 104;
    CouldNotFindCustomAttribute = 105;
    LegendarySkinDoesNotExist = 106;
    EmptySlot = 107;
    DifferentBase = 108;
    Contraband = 109;
    DataSetupError = 110;
    AlreadyMaxProgressionPoints = 111;
    LootPoolNull = 112;
    ObjectNull = 113;
    NotAvailable = 114;
    NotFinished = 115;
    ObjectAlreadyInPPCCard = 116;
    NotEnoughSigils = 117;
    NotEnoughSigilsSpent = 118;
  }
  FP.Hunt.MetaReqRsp.Code code = 1;
  FP.Hunt.MetaBloodLineUpdate update = 2;
  int64 time_stamp = 3;
  FP.Hunt.MetaReqType req_type = 4;
  int64 param_int64 = 5;
  repeated int64 list_int64 = 6;
  repeated string list_string = 7;
  bool param_bool = 8;
}
message MetaQuickPlayCharsRsp {
  repeated FP.Hunt.MetaSerPlayerChar chars = 1;
}
message MetaServerNotification {
  FP.Hunt.MetaBloodLineUpdate blood_line_update = 1;
  FP.Hunt.MetaMissionBagUpdate mission_bag_update = 2;
  FP.Hunt.LogDebugMsg debug_log = 3;
}
