syntax = "proto3";
package FP;

import "ProtocolVersion.proto";
import "ServiceExt.proto";
import "EUserType.proto";

enum EVersionUpdateErrorCode {
  option allow_alias = true;
  eVU_UpdateOk = 0;
  eVU_UpdateError = 1;
  eVU_HashNotFoundForVersion = 1;
  eVU_PakNotFound = 1;
  eVU_CrcNotFound = 1;
}
message RequestVersionUpdateReq {
  FP.Version game_version = 1;
  FP.EUserType platform = 2;
}
message RequestVersionUpdateResult {
  string livedata_hash = 1;
  string livedata_cdn_url = 2;
  string livedata_crc = 3;
  FP.EVersionUpdateErrorCode code = 4;
}
message BroadcastVersionUpdateMessage {
  repeated FP.Version game_version = 1;
}
service RequestVersionUpdate {
  rpc RequestVersionUpdate(FP.RequestVersionUpdateReq) returns (FP.RequestVersionUpdateResult);
}
