"""Generate docs/API_SURFACE.md from the recovered schema.

    python tools/gen_api_surface.py

Everything in the output is derived from the descriptors, so it stays honest across
game patches: re-run it after dump_protos.py rather than editing the markdown.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import schema

SCALARS = {
    1: "double", 2: "float", 3: "int64", 4: "uint64", 5: "int32", 6: "fixed64",
    7: "fixed32", 8: "bool", 9: "string", 12: "bytes", 13: "uint32", 15: "sfixed32",
    16: "sfixed64", 17: "sint32", 18: "sint64",
}

# Messages worth spelling out field-by-field: these are the ones a tracker consumes.
DETAIL = [
    "FP.Hunt.MetaMissionBag",
    "FP.Hunt.MetaMissionBag.Player",
    "FP.Hunt.MetaMissionBag.Team",
    "FP.Hunt.AccoladeWon",
    "FP.Hunt.MetaBloodLineStats",
    "FP.Hunt.MetaBloodLineSkillRating",
    "FP.Hunt.MetaBloodLineCoreInfo",
    "FP.Hunt.MetaQuickPlayStats",
    "FP.Hunt.MetaCharStats",
    "FP.Hunt.MetaLastMatchInfo",
    "FP.Hunt.MetaPublicInfo",
    "FP.Hunt.LeaderboardItem",
    "FP.Hunt.UserStatsCommon",
    "FP.ReqHeader",
    "FP.ResHeader",
]


def field_type(f) -> str:
    return f.type_name.lstrip(".") if f.type_name else SCALARS.get(f.type, f"type{f.type}")


def field_str(f) -> str:
    label = "repeated " if f.label == 3 else ""
    return f"{label}{field_type(f)}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--proto", type=Path, default=Path("proto"))
    ap.add_argument("--out", type=Path, default=Path("docs/API_SURFACE.md"))
    args = ap.parse_args()

    proto_dir = schema.latest_version_dir(args.proto)
    fds = schema.load(proto_dir)
    manifest_path = proto_dir / "manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.is_file() else {}
    version = manifest.get("game_version", proto_dir.name)

    files = [fd for fd in fds.file if not fd.name.startswith(("google/", "opentelemetry/"))]
    messages = {}
    for fd in files:
        for full, msg in schema.walk_messages(fd):
            messages[full] = (fd.name, msg)

    services = [(schema.qualified(fd, s.name), fd.name, s) for fd in files for s in fd.service]
    rpc_count = sum(len(s.method) for _, _, s in services)

    out: list[str] = [
        "# Hunt client API surface",
        "",
        f"Generated by `tools/gen_api_surface.py` from the schema recovered out of "
        f"`GameHunt.dll` at game version **{version}**. Do not hand-edit.",
        "",
        f"**{len(files)} files, {len(services)} services, {rpc_count} RPCs, "
        f"{len(messages)} messages.**",
        "",
        "Transport is Crytek's own framing (`FP.ReqHeader` / `FP.ResHeader`), not gRPC: "
        "no RPC here uses protobuf streaming. Subscriptions are instead plain unary calls "
        "that the server answers repeatedly, correlated by `ResHeader.unsubscribe_id` - "
        "`SubForNotifications`, `MissionUpdatesStream`, `EventsStateStream`, "
        "`MaintenanceStream`, `ChatStream`, `DsReadyStream` and `ReleasePackStream` all "
        "work that way. See [WIRE_FORMAT.md](WIRE_FORMAT.md).",
        "",
        "## Services",
        "",
    ]

    for full, filename, svc in sorted(services):
        out.append(f"### {full}")
        out.append("")
        out.append(f"`{filename}` - {len(svc.method)} RPCs")
        out.append("")
        out.append("| RPC | Request | Response |")
        out.append("|---|---|---|")
        for m in svc.method:
            req = ("stream " if m.client_streaming else "") + m.input_type.lstrip(".")
            rsp = ("stream " if m.server_streaming else "") + m.output_type.lstrip(".")
            out.append(f"| `{m.name}` | `{req}` | `{rsp}` |")
        out.append("")

    out += ["## Key messages", "", "The payloads a stats tracker actually reads.", ""]
    for name in DETAIL:
        if name not in messages:
            out += [f"### {name}", "", "*not present in this build*", ""]
            continue
        filename, msg = messages[name]
        out += [f"### {name}", "", f"`{filename}`", "", "| # | Field | Type |", "|---|---|---|"]
        for f in sorted(msg.field, key=lambda f: f.number):
            out.append(f"| {f.number} | `{f.name}` | `{field_str(f)}` |")
        out.append("")

    out += ["## All messages", "", "| Message | File | Fields |", "|---|---|---|"]
    for name in sorted(messages):
        filename, msg = messages[name]
        out.append(f"| `{name}` | {filename} | {len(msg.field)} |")
    out.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {args.out} ({len(services)} services, {rpc_count} rpcs, {len(messages)} messages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
